version : '3'
services:

  springboot_docker_demo:
        image: "wenthywang/docker_springboot"
        ports:
                - "8088:8088"
        environment:
          JAVA_OPTS: -Xmx256m -Xms256m
        volumes:
            - /usr/local/wwh/logs:/log