version : '3'
services:
  springboot_docker_demo:
        image: "wenthywang/demo"
        ports:
                - "8082:8082"
        environment:
          JAVA_OPTS: -Xmx256m -Xms256m
        volumes:
            - /usr/local/wwh/sb/logs:/log
        container_name: wenthywang-demo
        restart: always