spring:
  application:
    name: springboot_demo_docker
  profiles:
      active: dev
  datasource:
    url: jdbc:mysql://111.230.24.31:33060/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: root
    password: wwh13660783361
    driver-class-name: com.mysql.jdbc.Driver
    tomcat.max-active: 10
    tomcat.min-idle: 1
    tomcat.max-idle: 5
---
spring:
  config:
    activate:
      on-profile: dev
server:
    port: 8082

---
spring:
  config:
    activate:
      on-profile: docker
server:
  port: 8082

